//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ZhiWa.proto
// Note: requires additional types generated from: public.proto
using @public;

namespace ZhiWa
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgGlobal")]
  public partial class MsgGlobal : global::ProtoBuf.IExtensible
  {
    public MsgGlobal() {}
    

    private MsgSession _session = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"session", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MsgSession session
    {
      get { return _session; }
      set { _session = value; }
    }

    private MsgLogin _login = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"login", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MsgLogin login
    {
      get { return _login; }
      set { _login = value; }
    }

    private MsgPlayerInfo _player_info = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"player_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MsgPlayerInfo player_info
    {
      get { return _player_info; }
      set { _player_info = value; }
    }

    private MsgGoldPlayground _gold_playground = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"gold_playground", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MsgGoldPlayground gold_playground
    {
      get { return _gold_playground; }
      set { _gold_playground = value; }
    }

    private MsgGoldOutPlayer _gold_out_player = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"gold_out_player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MsgGoldOutPlayer gold_out_player
    {
      get { return _gold_out_player; }
      set { _gold_out_player = value; }
    }

    private MsgGuandanRoom _guandan_room = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"guandan_room", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MsgGuandanRoom guandan_room
    {
      get { return _guandan_room; }
      set { _guandan_room = value; }
    }

    private MsgGoldReadyPlayer _gold_ready_player = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"gold_ready_player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MsgGoldReadyPlayer gold_ready_player
    {
      get { return _gold_ready_player; }
      set { _gold_ready_player = value; }
    }

    private MsgAction _action = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"action", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MsgAction action
    {
      get { return _action; }
      set { _action = value; }
    }

    private MsgPropsInfo _props_info = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"props_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MsgPropsInfo props_info
    {
      get { return _props_info; }
      set { _props_info = value; }
    }

    private MsgChangeSeatInfo _change_seat_info = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"change_seat_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MsgChangeSeatInfo change_seat_info
    {
      get { return _change_seat_info; }
      set { _change_seat_info = value; }
    }

    private MsgTributeInfo _tribute_info = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"tribute_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MsgTributeInfo tribute_info
    {
      get { return _tribute_info; }
      set { _tribute_info = value; }
    }

    private MsgRoomInfo _room_info = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"room_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MsgRoomInfo room_info
    {
      get { return _room_info; }
      set { _room_info = value; }
    }

    private ulong _actionId = default(ulong);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"actionId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong actionId
    {
      get { return _actionId; }
      set { _actionId = value; }
    }

    private MsgDisRoomInfo _dis_room_info = null;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"dis_room_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MsgDisRoomInfo dis_room_info
    {
      get { return _dis_room_info; }
      set { _dis_room_info = value; }
    }

    private MsgIpConfirm _ip_confirm = null;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"ip_confirm", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MsgIpConfirm ip_confirm
    {
      get { return _ip_confirm; }
      set { _ip_confirm = value; }
    }

    private MsgCardTip _card_tip = null;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"card_tip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MsgCardTip card_tip
    {
      get { return _card_tip; }
      set { _card_tip = value; }
    }

    private MsgEmotionInfo _emotion_info = null;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"emotion_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MsgEmotionInfo emotion_info
    {
      get { return _emotion_info; }
      set { _emotion_info = value; }
    }

    private string _showCardFailDetail = "";
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"showCardFailDetail", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string showCardFailDetail
    {
      get { return _showCardFailDetail; }
      set { _showCardFailDetail = value; }
    }

    private MsgGameError _game_error = null;
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"game_error", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MsgGameError game_error
    {
      get { return _game_error; }
      set { _game_error = value; }
    }
    private readonly global::System.Collections.Generic.List<MsgHorseInfo> _horse_info = new global::System.Collections.Generic.List<MsgHorseInfo>();
    [global::ProtoBuf.ProtoMember(20, Name=@"horse_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MsgHorseInfo> horse_info
    {
      get { return _horse_info; }
    }
  

    private string _room_id = "";
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"room_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string room_id
    {
      get { return _room_id; }
      set { _room_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgGuandanRoom")]
  public partial class MsgGuandanRoom : global::ProtoBuf.IExtensible
  {
    public MsgGuandanRoom() {}
    

    private MsgRoomInfo _room_info = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"room_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MsgRoomInfo room_info
    {
      get { return _room_info; }
      set { _room_info = value; }
    }
    private readonly global::System.Collections.Generic.List<MsgPlayerInfo> _player_info = new global::System.Collections.Generic.List<MsgPlayerInfo>();
    [global::ProtoBuf.ProtoMember(5, Name=@"player_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MsgPlayerInfo> player_info
    {
      get { return _player_info; }
    }
  

    private MsgGameInfo _game_info = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"game_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MsgGameInfo game_info
    {
      get { return _game_info; }
      set { _game_info = value; }
    }

    private MsgPlayerCleanInfo _player_clean_info = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"player_clean_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MsgPlayerCleanInfo player_clean_info
    {
      get { return _player_clean_info; }
      set { _player_clean_info = value; }
    }

    private MsgGameoverCard _game_over_card = null;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"game_over_card", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MsgGameoverCard game_over_card
    {
      get { return _game_over_card; }
      set { _game_over_card = value; }
    }
    private readonly global::System.Collections.Generic.List<MsgGameOverInfo> _game_over_info = new global::System.Collections.Generic.List<MsgGameOverInfo>();
    [global::ProtoBuf.ProtoMember(8, Name=@"game_over_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MsgGameOverInfo> game_over_info
    {
      get { return _game_over_info; }
    }
  

    private MsgAction _action = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"action", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MsgAction action
    {
      get { return _action; }
      set { _action = value; }
    }
    private readonly global::System.Collections.Generic.List<MsgSendCardInfo> _send_card_info = new global::System.Collections.Generic.List<MsgSendCardInfo>();
    [global::ProtoBuf.ProtoMember(10, Name=@"send_card_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MsgSendCardInfo> send_card_info
    {
      get { return _send_card_info; }
    }
  
    private readonly global::System.Collections.Generic.List<MsgFightingCardLog> _fighting_card_log = new global::System.Collections.Generic.List<MsgFightingCardLog>();
    [global::ProtoBuf.ProtoMember(11, Name=@"fighting_card_log", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MsgFightingCardLog> fighting_card_log
    {
      get { return _fighting_card_log; }
    }
  

    private MsgChangeSeatInfo _change_seat_info = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"change_seat_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MsgChangeSeatInfo change_seat_info
    {
      get { return _change_seat_info; }
      set { _change_seat_info = value; }
    }

    private MsgPropsInfo _props_info = null;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"props_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MsgPropsInfo props_info
    {
      get { return _props_info; }
      set { _props_info = value; }
    }
    private readonly global::System.Collections.Generic.List<MsgSameIpPlayer> _same_ip_player = new global::System.Collections.Generic.List<MsgSameIpPlayer>();
    [global::ProtoBuf.ProtoMember(14, Name=@"same_ip_player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MsgSameIpPlayer> same_ip_player
    {
      get { return _same_ip_player; }
    }
  
    private readonly global::System.Collections.Generic.List<MsgActionLog> _action_log = new global::System.Collections.Generic.List<MsgActionLog>();
    [global::ProtoBuf.ProtoMember(15, Name=@"action_log", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MsgActionLog> action_log
    {
      get { return _action_log; }
    }
  

    private string _voiceName = "";
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"voiceName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string voiceName
    {
      get { return _voiceName; }
      set { _voiceName = value; }
    }

    private MsgTributeInfo _game_tribute_info = null;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"game_tribute_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MsgTributeInfo game_tribute_info
    {
      get { return _game_tribute_info; }
      set { _game_tribute_info = value; }
    }
    private readonly global::System.Collections.Generic.List<MsgTotalScore> _game_totalScore = new global::System.Collections.Generic.List<MsgTotalScore>();
    [global::ProtoBuf.ProtoMember(18, Name=@"game_totalScore", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MsgTotalScore> game_totalScore
    {
      get { return _game_totalScore; }
    }
  

    private uint _Tag = default(uint);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"Tag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Tag
    {
      get { return _Tag; }
      set { _Tag = value; }
    }
    private readonly global::System.Collections.Generic.List<MsgRecord> _record = new global::System.Collections.Generic.List<MsgRecord>();
    [global::ProtoBuf.ProtoMember(21, Name=@"record", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MsgRecord> record
    {
      get { return _record; }
    }
  
    private readonly global::System.Collections.Generic.List<MsgLast3Card> _last3card = new global::System.Collections.Generic.List<MsgLast3Card>();
    [global::ProtoBuf.ProtoMember(22, Name=@"last3card", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MsgLast3Card> last3card
    {
      get { return _last3card; }
    }
  

    private MsgDisRoomInfo _dissRoomInfo = null;
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"dissRoomInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MsgDisRoomInfo dissRoomInfo
    {
      get { return _dissRoomInfo; }
      set { _dissRoomInfo = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _djCards = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(24, Name=@"djCards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> djCards
    {
      get { return _djCards; }
    }
  

    private bool _ybq = default(bool);
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"ybq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool ybq
    {
      get { return _ybq; }
      set { _ybq = value; }
    }

    private MsgTalk _msg_talk = null;
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"msg_talk", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MsgTalk msg_talk
    {
      get { return _msg_talk; }
      set { _msg_talk = value; }
    }

    private MsgGoldReadyPlayer _gold_ready_player = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"gold_ready_player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MsgGoldReadyPlayer gold_ready_player
    {
      get { return _gold_ready_player; }
      set { _gold_ready_player = value; }
    }

    private MsgGoldPlayground _gold_playground = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"gold_playground", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MsgGoldPlayground gold_playground
    {
      get { return _gold_playground; }
      set { _gold_playground = value; }
    }
    private readonly global::System.Collections.Generic.List<MsgTuoSan> _tuo_san = new global::System.Collections.Generic.List<MsgTuoSan>();
    [global::ProtoBuf.ProtoMember(27, Name=@"tuo_san", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MsgTuoSan> tuo_san
    {
      get { return _tuo_san; }
    }
  
    private readonly global::System.Collections.Generic.List<MsgBieSan> _bie_san = new global::System.Collections.Generic.List<MsgBieSan>();
    [global::ProtoBuf.ProtoMember(28, Name=@"bie_san", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MsgBieSan> bie_san
    {
      get { return _bie_san; }
    }
  
    private readonly global::System.Collections.Generic.List<MsgBombGoal> _bomb_goal = new global::System.Collections.Generic.List<MsgBombGoal>();
    [global::ProtoBuf.ProtoMember(29, Name=@"bomb_goal", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MsgBombGoal> bomb_goal
    {
      get { return _bomb_goal; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgBombGoal")]
  public partial class MsgBombGoal : global::ProtoBuf.IExtensible
  {
    public MsgBombGoal() {}
    

    private ulong _pid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong pid
    {
      get { return _pid; }
      set { _pid = value; }
    }

    private int _goal = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"goal", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int goal
    {
      get { return _goal; }
      set { _goal = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgTuoSan")]
  public partial class MsgTuoSan : global::ProtoBuf.IExtensible
  {
    public MsgTuoSan() {}
    

    private ulong _pid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong pid
    {
      get { return _pid; }
      set { _pid = value; }
    }

    private uint _num = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint num
    {
      get { return _num; }
      set { _num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgBieSan")]
  public partial class MsgBieSan : global::ProtoBuf.IExtensible
  {
    public MsgBieSan() {}
    

    private ulong _pid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong pid
    {
      get { return _pid; }
      set { _pid = value; }
    }

    private uint _num = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint num
    {
      get { return _num; }
      set { _num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgLast3Card")]
  public partial class MsgLast3Card : global::ProtoBuf.IExtensible
  {
    public MsgLast3Card() {}
    

    private ulong _player_id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _card = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"card", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> card
    {
      get { return _card; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgGdEnding")]
  public partial class MsgGdEnding : global::ProtoBuf.IExtensible
  {
    public MsgGdEnding() {}
    

    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private readonly global::System.Collections.Generic.List<ulong> _player_id = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(2, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> player_id
    {
      get { return _player_id; }
    }
  

    private uint _win = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"win", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint win
    {
      get { return _win; }
      set { _win = value; }
    }

    private uint _win_win = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"win_win", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint win_win
    {
      get { return _win_win; }
      set { _win_win = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgHorseInfo")]
  public partial class MsgHorseInfo : global::ProtoBuf.IExtensible
  {
    public MsgHorseInfo() {}
    

    private string _horse_id = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"horse_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string horse_id
    {
      get { return _horse_id; }
      set { _horse_id = value; }
    }

    private string _enable_time = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"enable_time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string enable_time
    {
      get { return _enable_time; }
      set { _enable_time = value; }
    }

    private string _ineffect_time = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"ineffect_time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ineffect_time
    {
      get { return _ineffect_time; }
      set { _ineffect_time = value; }
    }

    private string _send_time = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"send_time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string send_time
    {
      get { return _send_time; }
      set { _send_time = value; }
    }

    private uint _perWaveInteval = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"perWaveInteval", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint perWaveInteval
    {
      get { return _perWaveInteval; }
      set { _perWaveInteval = value; }
    }

    private uint _intervalTime = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"intervalTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint intervalTime
    {
      get { return _intervalTime; }
      set { _intervalTime = value; }
    }

    private uint _perWaveNumber = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"perWaveNumber", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint perWaveNumber
    {
      get { return _perWaveNumber; }
      set { _perWaveNumber = value; }
    }

    private string _content = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgRecord")]
  public partial class MsgRecord : global::ProtoBuf.IExtensible
  {
    public MsgRecord() {}
    

    private uint _roomCode = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roomCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint roomCode
    {
      get { return _roomCode; }
      set { _roomCode = value; }
    }

    private TGuanDanGameType _game_type = TGuanDanGameType.TGuanDanGameTypeNull;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"game_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(TGuanDanGameType.TGuanDanGameTypeNull)]
    public TGuanDanGameType game_type
    {
      get { return _game_type; }
      set { _game_type = value; }
    }

    private string _end_time = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"end_time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string end_time
    {
      get { return _end_time; }
      set { _end_time = value; }
    }
    private readonly global::System.Collections.Generic.List<MsgPlayerInfo> _player_info = new global::System.Collections.Generic.List<MsgPlayerInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"player_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MsgPlayerInfo> player_info
    {
      get { return _player_info; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgDisRoomInfo")]
  public partial class MsgDisRoomInfo : global::ProtoBuf.IExtensible
  {
    public MsgDisRoomInfo() {}
    
    private readonly global::System.Collections.Generic.List<ulong> _dissRoomPlayer = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(1, Name=@"dissRoomPlayer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> dissRoomPlayer
    {
      get { return _dissRoomPlayer; }
    }
  

    private ulong _voteFirst = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"voteFirst", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong voteFirst
    {
      get { return _voteFirst; }
      set { _voteFirst = value; }
    }

    private string _voteTime = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"voteTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string voteTime
    {
      get { return _voteTime; }
      set { _voteTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgGameoverCard")]
  public partial class MsgGameoverCard : global::ProtoBuf.IExtensible
  {
    public MsgGameoverCard() {}
    
    private readonly global::System.Collections.Generic.List<MsgSendCardInfo> _send_card_info = new global::System.Collections.Generic.List<MsgSendCardInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"send_card_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MsgSendCardInfo> send_card_info
    {
      get { return _send_card_info; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgIpConfirm")]
  public partial class MsgIpConfirm : global::ProtoBuf.IExtensible
  {
    public MsgIpConfirm() {}
    

    private ulong _player_id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private readonly global::System.Collections.Generic.List<ulong> _pids = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(2, Name=@"pids", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> pids
    {
      get { return _pids; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgTotalScore")]
  public partial class MsgTotalScore : global::ProtoBuf.IExtensible
  {
    public MsgTotalScore() {}
    

    private ulong _player_id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }

    private int _play_goal = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"play_goal", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int play_goal
    {
      get { return _play_goal; }
      set { _play_goal = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgTributeInfo")]
  public partial class MsgTributeInfo : global::ProtoBuf.IExtensible
  {
    public MsgTributeInfo() {}
    
    private readonly global::System.Collections.Generic.List<ulong> _jg_player_id = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(1, Name=@"jg_player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> jg_player_id
    {
      get { return _jg_player_id; }
    }
  
    private readonly global::System.Collections.Generic.List<ulong> _bjg_player_id = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(2, Name=@"bjg_player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> bjg_player_id
    {
      get { return _bjg_player_id; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _jgpz_card = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(3, Name=@"jgpz_card", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> jgpz_card
    {
      get { return _jgpz_card; }
    }
  

    private uint _hgpz_card = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"hgpz_card", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint hgpz_card
    {
      get { return _hgpz_card; }
      set { _hgpz_card = value; }
    }

    private uint _kgbs_tag = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"kgbs_tag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint kgbs_tag
    {
      get { return _kgbs_tag; }
      set { _kgbs_tag = value; }
    }

    private uint _start_tag = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"start_tag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint start_tag
    {
      get { return _start_tag; }
      set { _start_tag = value; }
    }

    private uint _jgpz_card_native = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"jgpz_card_native", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint jgpz_card_native
    {
      get { return _jgpz_card_native; }
      set { _jgpz_card_native = value; }
    }

    private uint _hgpz_card_native = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"hgpz_card_native", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint hgpz_card_native
    {
      get { return _hgpz_card_native; }
      set { _hgpz_card_native = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgGameError")]
  public partial class MsgGameError : global::ProtoBuf.IExtensible
  {
    public MsgGameError() {}
    

    private MsgErrors _errId = MsgErrors.MsgCreateRoomErr;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"errId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(MsgErrors.MsgCreateRoomErr)]
    public MsgErrors errId
    {
      get { return _errId; }
      set { _errId = value; }
    }

    private ulong _player_id = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgActionLog")]
  public partial class MsgActionLog : global::ProtoBuf.IExtensible
  {
    public MsgActionLog() {}
    

    private ulong _player_id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _card = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"card", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> card
    {
      get { return _card; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgSameIpPlayer")]
  public partial class MsgSameIpPlayer : global::ProtoBuf.IExtensible
  {
    public MsgSameIpPlayer() {}
    
    private readonly global::System.Collections.Generic.List<ulong> _pid = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(1, Name=@"pid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> pid
    {
      get { return _pid; }
    }
  

    private string _ip = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ip
    {
      get { return _ip; }
      set { _ip = value; }
    }

    private ulong _player_id = default(ulong);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }

    private uint _isIpConfirm = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"isIpConfirm", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint isIpConfirm
    {
      get { return _isIpConfirm; }
      set { _isIpConfirm = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgRoomInfo")]
  public partial class MsgRoomInfo : global::ProtoBuf.IExtensible
  {
    public MsgRoomInfo() {}
    

    private uint _roomCode = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roomCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint roomCode
    {
      get { return _roomCode; }
      set { _roomCode = value; }
    }

    private TGuanDanCardUseType _card_use_type = TGuanDanCardUseType.TGuanDanCardUseTypeCreater;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"card_use_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(TGuanDanCardUseType.TGuanDanCardUseTypeCreater)]
    public TGuanDanCardUseType card_use_type
    {
      get { return _card_use_type; }
      set { _card_use_type = value; }
    }

    private uint _game_num = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"game_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint game_num
    {
      get { return _game_num; }
      set { _game_num = value; }
    }

    private ulong _creater_id = default(ulong);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"creater_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong creater_id
    {
      get { return _creater_id; }
      set { _creater_id = value; }
    }

    private uint _creater_pay = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"creater_pay", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint creater_pay
    {
      get { return _creater_pay; }
      set { _creater_pay = value; }
    }

    private uint _other_pay = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"other_pay", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint other_pay
    {
      get { return _other_pay; }
      set { _other_pay = value; }
    }

    private TGuanDanGameType _game_type = TGuanDanGameType.TGuanDanGameTypeNull;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"game_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(TGuanDanGameType.TGuanDanGameTypeNull)]
    public TGuanDanGameType game_type
    {
      get { return _game_type; }
      set { _game_type = value; }
    }
    private readonly global::System.Collections.Generic.List<MsgGdEnding> _gd_ending = new global::System.Collections.Generic.List<MsgGdEnding>();
    [global::ProtoBuf.ProtoMember(8, Name=@"gd_ending", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MsgGdEnding> gd_ending
    {
      get { return _gd_ending; }
    }
  

    private uint _money_pay = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"money_pay", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint money_pay
    {
      get { return _money_pay; }
      set { _money_pay = value; }
    }

    private string _server_host = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"server_host", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string server_host
    {
      get { return _server_host; }
      set { _server_host = value; }
    }

    private string _server_port = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"server_port", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string server_port
    {
      get { return _server_port; }
      set { _server_port = value; }
    }

    private bool _shunzi = default(bool);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"shunzi", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool shunzi
    {
      get { return _shunzi; }
      set { _shunzi = value; }
    }

    private bool _bombGoal = default(bool);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"bombGoal", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool bombGoal
    {
      get { return _bombGoal; }
      set { _bombGoal = value; }
    }

    private bool _tuosan = default(bool);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"tuosan", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool tuosan
    {
      get { return _tuosan; }
      set { _tuosan = value; }
    }

    private bool _biesan = default(bool);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"biesan", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool biesan
    {
      get { return _biesan; }
      set { _biesan = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgPlayerInfo")]
  public partial class MsgPlayerInfo : global::ProtoBuf.IExtensible
  {
    public MsgPlayerInfo() {}
    

    private ulong _player_id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }

    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private string _head_portrait = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"head_portrait", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string head_portrait
    {
      get { return _head_portrait; }
      set { _head_portrait = value; }
    }

    private uint _sex = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sex
    {
      get { return _sex; }
      set { _sex = value; }
    }

    private uint _money = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint money
    {
      get { return _money; }
      set { _money = value; }
    }

    private string _ip = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ip
    {
      get { return _ip; }
      set { _ip = value; }
    }

    private uint _roomCode = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"roomCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint roomCode
    {
      get { return _roomCode; }
      set { _roomCode = value; }
    }

    private uint _remaindCarsNum = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"remaindCarsNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint remaindCarsNum
    {
      get { return _remaindCarsNum; }
      set { _remaindCarsNum = value; }
    }

    private int _goal = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"goal", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int goal
    {
      get { return _goal; }
      set { _goal = value; }
    }

    private uint _upgrade_card = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"upgrade_card", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint upgrade_card
    {
      get { return _upgrade_card; }
      set { _upgrade_card = value; }
    }

    private uint _teamType = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"teamType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint teamType
    {
      get { return _teamType; }
      set { _teamType = value; }
    }

    private string _ipAds = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"ipAds", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ipAds
    {
      get { return _ipAds; }
      set { _ipAds = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgGameInfo")]
  public partial class MsgGameInfo : global::ProtoBuf.IExtensible
  {
    public MsgGameInfo() {}
    

    private uint _game_id = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"game_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint game_id
    {
      get { return _game_id; }
      set { _game_id = value; }
    }

    private uint _game_index = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"game_index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint game_index
    {
      get { return _game_index; }
      set { _game_index = value; }
    }

    private uint _light_card = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"light_card", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint light_card
    {
      get { return _light_card; }
      set { _light_card = value; }
    }
    private readonly global::System.Collections.Generic.List<ulong> _light_player_id = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(4, Name=@"light_player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> light_player_id
    {
      get { return _light_player_id; }
    }
  
    private readonly global::System.Collections.Generic.List<ulong> _fight_player_id = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(5, Name=@"fight_player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> fight_player_id
    {
      get { return _fight_player_id; }
    }
  

    private uint _game_joker = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"game_joker", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint game_joker
    {
      get { return _game_joker; }
      set { _game_joker = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgAction")]
  public partial class MsgAction : global::ProtoBuf.IExtensible
  {
    public MsgAction() {}
    

    private ulong _last_action_id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"last_action_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong last_action_id
    {
      get { return _last_action_id; }
      set { _last_action_id = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _last_card = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"last_card", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> last_card
    {
      get { return _last_card; }
    }
  

    private uint _last_key = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"last_key", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint last_key
    {
      get { return _last_key; }
      set { _last_key = value; }
    }

    private TGuanDanCT _last_ct = TGuanDanCT.CT_Null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"last_ct", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(TGuanDanCT.CT_Null)]
    public TGuanDanCT last_ct
    {
      get { return _last_ct; }
      set { _last_ct = value; }
    }

    private MsgActionType _action_type = MsgActionType.MsgActionTypeNormal;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"action_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(MsgActionType.MsgActionTypeNormal)]
    public MsgActionType action_type
    {
      get { return _action_type; }
      set { _action_type = value; }
    }

    private ulong _action_id = default(ulong);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"action_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong action_id
    {
      get { return _action_id; }
      set { _action_id = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _action_card = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(7, Name=@"action_card", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> action_card
    {
      get { return _action_card; }
    }
  

    private uint _action_key = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"action_key", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint action_key
    {
      get { return _action_key; }
      set { _action_key = value; }
    }

    private TGuanDanCT _action_ct = TGuanDanCT.CT_Null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"action_ct", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(TGuanDanCT.CT_Null)]
    public TGuanDanCT action_ct
    {
      get { return _action_ct; }
      set { _action_ct = value; }
    }

    private ulong _last_operation_pid = default(ulong);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"last_operation_pid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong last_operation_pid
    {
      get { return _last_operation_pid; }
      set { _last_operation_pid = value; }
    }
    private readonly global::System.Collections.Generic.List<MsgCardGroup> _cardGroup = new global::System.Collections.Generic.List<MsgCardGroup>();
    [global::ProtoBuf.ProtoMember(11, Name=@"cardGroup", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MsgCardGroup> cardGroup
    {
      get { return _cardGroup; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgCardGroup")]
  public partial class MsgCardGroup : global::ProtoBuf.IExtensible
  {
    public MsgCardGroup() {}
    
    private readonly global::System.Collections.Generic.List<uint> _card = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"card", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> card
    {
      get { return _card; }
    }
  

    private TGuanDanCT _ct = TGuanDanCT.CT_Null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ct", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(TGuanDanCT.CT_Null)]
    public TGuanDanCT ct
    {
      get { return _ct; }
      set { _ct = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgCardTip")]
  public partial class MsgCardTip : global::ProtoBuf.IExtensible
  {
    public MsgCardTip() {}
    
    private readonly global::System.Collections.Generic.List<MsgCardGroup> _cardGroup = new global::System.Collections.Generic.List<MsgCardGroup>();
    [global::ProtoBuf.ProtoMember(1, Name=@"cardGroup", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<MsgCardGroup> cardGroup
    {
      get { return _cardGroup; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgPlayerCleanInfo")]
  public partial class MsgPlayerCleanInfo : global::ProtoBuf.IExtensible
  {
    public MsgPlayerCleanInfo() {}
    

    private ulong _player_id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }

    private MsgGuandanGameRank _rank = MsgGuandanGameRank.MsgGuandanGameRankFirst;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(MsgGuandanGameRank.MsgGuandanGameRankFirst)]
    public MsgGuandanGameRank rank
    {
      get { return _rank; }
      set { _rank = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgGameOverInfo")]
  public partial class MsgGameOverInfo : global::ProtoBuf.IExtensible
  {
    public MsgGameOverInfo() {}
    

    private ulong _player_id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }

    private MsgGuandanGameRank _rank = MsgGuandanGameRank.MsgGuandanGameRankFirst;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(MsgGuandanGameRank.MsgGuandanGameRankFirst)]
    public MsgGuandanGameRank rank
    {
      get { return _rank; }
      set { _rank = value; }
    }

    private MsgGuandanGameGoal _goal = MsgGuandanGameGoal.MsgGuandanGameGoal12;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"goal", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(MsgGuandanGameGoal.MsgGuandanGameGoal12)]
    public MsgGuandanGameGoal goal
    {
      get { return _goal; }
      set { _goal = value; }
    }

    private uint _tuosan_num = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"tuosan_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint tuosan_num
    {
      get { return _tuosan_num; }
      set { _tuosan_num = value; }
    }

    private uint _biesan_num = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"biesan_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint biesan_num
    {
      get { return _biesan_num; }
      set { _biesan_num = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _boom_goal = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(6, Name=@"boom_goal", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> boom_goal
    {
      get { return _boom_goal; }
    }
  

    private uint _all_goal = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"all_goal", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint all_goal
    {
      get { return _all_goal; }
      set { _all_goal = value; }
    }

    private uint _upgrade_card = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"upgrade_card", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint upgrade_card
    {
      get { return _upgrade_card; }
      set { _upgrade_card = value; }
    }

    private uint _over = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"over", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint over
    {
      get { return _over; }
      set { _over = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgSendCardInfo")]
  public partial class MsgSendCardInfo : global::ProtoBuf.IExtensible
  {
    public MsgSendCardInfo() {}
    

    private ulong _player_id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }

    private uint _card_num = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"card_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint card_num
    {
      get { return _card_num; }
      set { _card_num = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _card = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(3, Name=@"card", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> card
    {
      get { return _card; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgFightingCardLog")]
  public partial class MsgFightingCardLog : global::ProtoBuf.IExtensible
  {
    public MsgFightingCardLog() {}
    

    private ulong _player_id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _old_card = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"old_card", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> old_card
    {
      get { return _old_card; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _new_card = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(3, Name=@"new_card", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> new_card
    {
      get { return _new_card; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgChangeSeatInfo")]
  public partial class MsgChangeSeatInfo : global::ProtoBuf.IExtensible
  {
    public MsgChangeSeatInfo() {}
    

    private ulong _apply_player_id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"apply_player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong apply_player_id
    {
      get { return _apply_player_id; }
      set { _apply_player_id = value; }
    }

    private ulong _to_player_id = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"to_player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong to_player_id
    {
      get { return _to_player_id; }
      set { _to_player_id = value; }
    }

    private uint _apply_result = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"apply_result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint apply_result
    {
      get { return _apply_result; }
      set { _apply_result = value; }
    }
    private readonly global::System.Collections.Generic.List<ulong> _seat = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(4, Name=@"seat", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> seat
    {
      get { return _seat; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgPropsInfo")]
  public partial class MsgPropsInfo : global::ProtoBuf.IExtensible
  {
    public MsgPropsInfo() {}
    

    private ulong _action_id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"action_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong action_id
    {
      get { return _action_id; }
      set { _action_id = value; }
    }

    private ulong _target_id = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"target_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong target_id
    {
      get { return _target_id; }
      set { _target_id = value; }
    }

    private MsgProps _propsId = MsgProps.MsgMsgPropsNull;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"propsId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(MsgProps.MsgMsgPropsNull)]
    public MsgProps propsId
    {
      get { return _propsId; }
      set { _propsId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgEmotionInfo")]
  public partial class MsgEmotionInfo : global::ProtoBuf.IExtensible
  {
    public MsgEmotionInfo() {}
    

    private ulong _action_id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"action_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong action_id
    {
      get { return _action_id; }
      set { _action_id = value; }
    }

    private MsgEmoticon _emoticonId = MsgEmoticon.MsgEmoticonNull;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"emoticonId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(MsgEmoticon.MsgEmoticonNull)]
    public MsgEmoticon emoticonId
    {
      get { return _emoticonId; }
      set { _emoticonId = value; }
    }

    private string _message = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgTalk")]
  public partial class MsgTalk : global::ProtoBuf.IExtensible
  {
    public MsgTalk() {}
    

    private ulong _action_id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"action_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong action_id
    {
      get { return _action_id; }
      set { _action_id = value; }
    }

    private uint _time = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint time
    {
      get { return _time; }
      set { _time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgGoldPlayground")]
  public partial class MsgGoldPlayground : global::ProtoBuf.IExtensible
  {
    public MsgGoldPlayground() {}
    

    private TGoldPlaygroundType _gold_playground_type = TGoldPlaygroundType.TGoldPlaygroundTypeNull;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"gold_playground_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(TGoldPlaygroundType.TGoldPlaygroundTypeNull)]
    public TGoldPlaygroundType gold_playground_type
    {
      get { return _gold_playground_type; }
      set { _gold_playground_type = value; }
    }

    private uint _min = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"min", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint min
    {
      get { return _min; }
      set { _min = value; }
    }

    private uint _cost = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"cost", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cost
    {
      get { return _cost; }
      set { _cost = value; }
    }

    private uint _base_gold = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"base_gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint base_gold
    {
      get { return _base_gold; }
      set { _base_gold = value; }
    }

    private uint _roomCode = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"roomCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint roomCode
    {
      get { return _roomCode; }
      set { _roomCode = value; }
    }

    private uint _roomId = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }

    private uint _type = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgGoldReadyPlayer")]
  public partial class MsgGoldReadyPlayer : global::ProtoBuf.IExtensible
  {
    public MsgGoldReadyPlayer() {}
    
    private readonly global::System.Collections.Generic.List<ulong> _pid = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(1, Name=@"pid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> pid
    {
      get { return _pid; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgGoldOutPlayer")]
  public partial class MsgGoldOutPlayer : global::ProtoBuf.IExtensible
  {
    public MsgGoldOutPlayer() {}
    

    private ulong _pid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong pid
    {
      get { return _pid; }
      set { _pid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"TGuanDanCardUseType")]
    public enum TGuanDanCardUseType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TGuanDanCardUseTypeCreater", Value=1)]
      TGuanDanCardUseTypeCreater = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TGuanDanCardUseTypeAa", Value=2)]
      TGuanDanCardUseTypeAa = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"TGuanDanGameType")]
    public enum TGuanDanGameType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TGuanDanGameTypeNull", Value=0)]
      TGuanDanGameTypeNull = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TGuanDanGameTypeZhuanDan", Value=1)]
      TGuanDanGameTypeZhuanDan = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TGuanDanGameTypeGuanDan", Value=2)]
      TGuanDanGameTypeGuanDan = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TGuanDanGameTypeGuanDan6", Value=3)]
      TGuanDanGameTypeGuanDan6 = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TGuanDanGameTypeGuanDan8", Value=4)]
      TGuanDanGameTypeGuanDan8 = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TGuanDanGameTypeGuanDan10", Value=5)]
      TGuanDanGameTypeGuanDan10 = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TGuanDanGameTypeGuanDanA", Value=6)]
      TGuanDanGameTypeGuanDanA = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TGuanDanGameTypeGold", Value=8)]
      TGuanDanGameTypeGold = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TZhuanQiang", Value=9)]
      TZhuanQiang = 9
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"TGuanDanGameNum")]
    public enum TGuanDanGameNum
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TGuanDanGameNumNull", Value=0)]
      TGuanDanGameNumNull = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TGuanDanGameNumMax", Value=1)]
      TGuanDanGameNumMax = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TGuanDanGameNum4", Value=4)]
      TGuanDanGameNum4 = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TGuanDanGameNum8", Value=8)]
      TGuanDanGameNum8 = 8
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MsgActionType")]
    public enum MsgActionType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgActionTypeNormal", Value=1)]
      MsgActionTypeNormal = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgActionTypeZhuang", Value=2)]
      MsgActionTypeZhuang = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgActionTypeJiefeng", Value=3)]
      MsgActionTypeJiefeng = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MsgGuandanGameRank")]
    public enum MsgGuandanGameRank
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgGuandanGameRankFirst", Value=1)]
      MsgGuandanGameRankFirst = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgGuandanGameRankSecond", Value=2)]
      MsgGuandanGameRankSecond = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgGuandanGameRankThird", Value=3)]
      MsgGuandanGameRankThird = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgGuandanGameRankLast", Value=4)]
      MsgGuandanGameRankLast = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgGuandanGameRankEmpty", Value=5)]
      MsgGuandanGameRankEmpty = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MsgGuandanGameGoal")]
    public enum MsgGuandanGameGoal
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgGuandanGameGoal12", Value=3)]
      MsgGuandanGameGoal12 = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgGuandanGameGoal13", Value=2)]
      MsgGuandanGameGoal13 = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgGuandanGameGoal14", Value=1)]
      MsgGuandanGameGoal14 = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgGuandanGameGoal23", Value=-1)]
      MsgGuandanGameGoal23 = -1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgGuandanGameGoal24", Value=-2)]
      MsgGuandanGameGoal24 = -2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgGuandanGameGoal34", Value=-3)]
      MsgGuandanGameGoal34 = -3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MsgGuandanDissRoomType")]
    public enum MsgGuandanDissRoomType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgGuandanOutByCreater", Value=1)]
      MsgGuandanOutByCreater = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgGuandanOutByPlayer", Value=2)]
      MsgGuandanOutByPlayer = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgGuandanDissInGame", Value=3)]
      MsgGuandanDissInGame = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"TGuanDanCT")]
    public enum TGuanDanCT
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CT_Null", Value=0)]
      CT_Null = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CT_SINGLE", Value=1)]
      CT_SINGLE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CT_DOUBLE", Value=2)]
      CT_DOUBLE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CT_THREE_TIAO", Value=3)]
      CT_THREE_TIAO = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CT_SHUN_ZI", Value=4)]
      CT_SHUN_ZI = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CT_HU_LU", Value=5)]
      CT_HU_LU = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CT_GANG_BAN", Value=6)]
      CT_GANG_BAN = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CT_LIANG_LIAN_DUI", Value=7)]
      CT_LIANG_LIAN_DUI = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CT_SI_ZHANG_BOMB", Value=8)]
      CT_SI_ZHANG_BOMB = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CT_WU_ZHANG_BOMB", Value=9)]
      CT_WU_ZHANG_BOMB = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CT_TONG_HUA_SHUN", Value=10)]
      CT_TONG_HUA_SHUN = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CT_LIU_ZHANG_BOMB", Value=11)]
      CT_LIU_ZHANG_BOMB = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CT_QI_ZHANG_BOMB", Value=12)]
      CT_QI_ZHANG_BOMB = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CT_BA_ZHANG_BOMB", Value=13)]
      CT_BA_ZHANG_BOMB = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CT_JIU_ZHANG_BOMB", Value=14)]
      CT_JIU_ZHANG_BOMB = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CT_SHI_ZHANG_BOMB", Value=15)]
      CT_SHI_ZHANG_BOMB = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CT_FOUR_KING", Value=16)]
      CT_FOUR_KING = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CT_BUCHU", Value=17)]
      CT_BUCHU = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CT_ERROR", Value=20)]
      CT_ERROR = 20
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MsgProps")]
    public enum MsgProps
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgMsgPropsNull", Value=-1)]
      MsgMsgPropsNull = -1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgPropsRose", Value=0)]
      MsgPropsRose = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgPropsEgg", Value=5)]
      MsgPropsEgg = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgPropsBeer", Value=15)]
      MsgPropsBeer = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgPropsBomb", Value=22)]
      MsgPropsBomb = 22,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgPropsBrick", Value=38)]
      MsgPropsBrick = 38,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgPropsKnife", Value=43)]
      MsgPropsKnife = 43,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgPropsYellowCorn", Value=58)]
      MsgPropsYellowCorn = 58,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgPropsBlackCorn", Value=59)]
      MsgPropsBlackCorn = 59,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgPropsIncense", Value=109)]
      MsgPropsIncense = 109,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgPropsGod", Value=158)]
      MsgPropsGod = 158
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MsgEmoticon")]
    public enum MsgEmoticon
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgEmoticonNull", Value=0)]
      MsgEmoticonNull = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgEmoticonComplain", Value=1)]
      MsgEmoticonComplain = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgEmoticonSorry", Value=2)]
      MsgEmoticonSorry = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgEmoticonShutUp", Value=3)]
      MsgEmoticonShutUp = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgEmoticonCry", Value=4)]
      MsgEmoticonCry = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgEmoticonGood", Value=5)]
      MsgEmoticonGood = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgEmoticonBlack", Value=6)]
      MsgEmoticonBlack = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgEmoticonLovely", Value=7)]
      MsgEmoticonLovely = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgEmoticonAmazed", Value=8)]
      MsgEmoticonAmazed = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgEmoticonQuestion", Value=9)]
      MsgEmoticonQuestion = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgEmoticonSaliva", Value=10)]
      MsgEmoticonSaliva = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgEmoticonSnail", Value=11)]
      MsgEmoticonSnail = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgEmoticonSmile", Value=12)]
      MsgEmoticonSmile = 12
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"MsgErrors")]
    public enum MsgErrors
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgCreateRoomErr", Value=1)]
      MsgCreateRoomErr = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgEnterRoomErr", Value=2)]
      MsgEnterRoomErr = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgApplyChangeSeatsErr", Value=3)]
      MsgApplyChangeSeatsErr = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgAgreeChangeSeatsErr", Value=4)]
      MsgAgreeChangeSeatsErr = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgDissRoomAgreeErr", Value=5)]
      MsgDissRoomAgreeErr = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgDissRoomDisAgreeErr", Value=6)]
      MsgDissRoomDisAgreeErr = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgDissRoomErr", Value=7)]
      MsgDissRoomErr = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgGdShowCardErr", Value=8)]
      MsgGdShowCardErr = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgHertBeatErr", Value=9)]
      MsgHertBeatErr = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgOutRoomByCreaterErr", Value=10)]
      MsgOutRoomByCreaterErr = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgOutRoomByPlayerErr", Value=11)]
      MsgOutRoomByPlayerErr = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgReadyForGdStartErr", Value=12)]
      MsgReadyForGdStartErr = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgReadForStartErr", Value=13)]
      MsgReadForStartErr = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgReconnectErr", Value=14)]
      MsgReconnectErr = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgShowCardErr", Value=15)]
      MsgShowCardErr = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgUsePropsErr", Value=16)]
      MsgUsePropsErr = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgCancleReadyForStartErr", Value=17)]
      MsgCancleReadyForStartErr = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgGameQuiteErr", Value=18)]
      MsgGameQuiteErr = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgGameTalkErr", Value=19)]
      MsgGameTalkErr = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgGameTotalScoreErr", Value=20)]
      MsgGameTotalScoreErr = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgGameTributeErr", Value=21)]
      MsgGameTributeErr = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgGameBackTributeErr", Value=22)]
      MsgGameBackTributeErr = 22,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgUseEmoticonErr", Value=23)]
      MsgUseEmoticonErr = 23,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgIpConfirmErr", Value=24)]
      MsgIpConfirmErr = 24,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgGoldPlaygroundEnterErr", Value=25)]
      MsgGoldPlaygroundEnterErr = 25
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"TGoldPlaygroundType")]
    public enum TGoldPlaygroundType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TGoldPlaygroundTypeNull", Value=0)]
      TGoldPlaygroundTypeNull = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TGoldPlaygroundType1", Value=1)]
      TGoldPlaygroundType1 = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TGoldPlaygroundType2", Value=2)]
      TGoldPlaygroundType2 = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TGoldPlaygroundType3", Value=3)]
      TGoldPlaygroundType3 = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TGoldPlaygroundType4", Value=4)]
      TGoldPlaygroundType4 = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ControlFlag")]
    public enum ControlFlag
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Normal", Value=1)]
      Normal = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HeartBeat", Value=2)]
      HeartBeat = 2
    }
  
}